name: "HW2 Shop API Tests"

# Запускаем тесты при изменении файлов в hw2/hw/
on:
  pull_request:
    branches: [ main ]
    paths: [ 'hw2/hw/**' ]
  push:
    branches: [ main ]
    paths: [ 'hw2/hw/**' ]

# jobs:
#   test-shop-api:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         python-version: ["3.12", "3.13"]
    
#     services:
#       postgres:
#         image: postgres:16
#         env:
#           POSTGRES_USER: shop_user
#           POSTGRES_PASSWORD: shop_password
#           POSTGRES_DB: shop_db
#           POSTGRES_INITDB_ARGS: "--encoding=UTF8"
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5
#         ports:
#           - 5445:5432
    
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4
    
#     - name: Set up Python ${{ matrix.python-version }}
#       uses: actions/setup-python@v4
#       with:
#         python-version: ${{ matrix.python-version }}
    
#     - name: Install dependencies
#       working-directory: hw2/hw
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt

#     - name: Run tests
#       working-directory: hw2/hw
#       env:
#         PYTHONPATH: ${{ github.workspace }}/hw2/hw
#         DATABASE_URL: postgresql+asyncpg://shop_user:shop_password@localhost:5445/shop_db
#       run: |
#         pytest tests/test_shop_api.py -v

jobs:
  test-hw2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      working-directory: hw2/hw
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      working-directory: hw2/hw
      env:
        PYTHONPATH: ${{ github.workspace }}/hw2/hw
      run: |
        pytest test_homework2.py -v
